
dependencies {
    api "org.apache.curator:curator-recipes:$curatorVersion"
    api project(":eventuate-common-coordination-leadership")
    api "org.slf4j:slf4j-api:$slf4jVersion"

    testImplementation project(":eventuate-common-coordination-leadership-tests")
    testImplementation "org.testcontainers:testcontainers:$testContainersVersion"

    testImplementation project(":eventuate-common-testcontainers")
    testImplementation "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
}

test {
    forkEvery 1
    useJUnitPlatform()
}
