
dependencies {
    api project (":eventuate-common-json-mapper")

    api "com.mysql:mysql-connector-j:$mysqlConnectorVersion"
    api ("org.postgresql:postgresql:$postgresqlVersion") {
        exclude group: "org.slf4j", module: "slf4j-simple"
    }
    runtimeOnly "com.microsoft.sqlserver:mssql-jdbc:$mssqlJdbcVersion"

    testImplementation "com.zaxxer:HikariCP:$hikariCpVersion"
    testImplementation "org.assertj:assertj-core:$assertjVersion"

}

test {
    forkEvery 1
    useJUnitPlatform()
}
