version: '3'
services:
  mssql-migration:
    image: mcr.microsoft.com/mssql-tools
    environment:
      TRAM_DB_SERVER: "mssql"
      TRAM_SA_PASSWORD: "Eventuate123!"
      TRAM_DB: "eventuate"
      TRAM_SCHEMA: "eventuate"
    volumes:
      - ${DB_ID_MIGRATION_DIR?}:/scripts
    working_dir: /scripts
    entrypoint: [ "bash", "./entrypoint.sh"]