version: 2.1
orbs:
  build-and-test:
    jobs:
      build-and-test:
        parameters:
          script:
            description: the script to execute
            type: string
        machine: true
        working_directory: ~/eventuate-common
        steps:
          - checkout
          - restore_cache:
              keys:
                - eventuate-common-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                - eventuate-common-
          - run:
              command: |
                ./.circleci/upgrade-docker-compose.sh
                ./gradlew testClasses aggregateJavaDocs
          - save_cache:
              paths:
                - ~/.gradle
              key: eventuate-common-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          - run: <<parameters.script>>
          - run:
              name: Save test results
              command: ./.circleci/save-containers-and-tests.sh
              when: always
          - store_test_results:
              path: ~/junit
          - store_artifacts:
              path: ~/junit
          - store_artifacts:
              path: ~/container-logs
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build-and-test/build-and-test:
          name: build-and-test-mysql-mysql-8-multi-arch
          script: ./install-buildx-and-build-and-test-all-mysql8-multi-arch.sh
      - build-and-test/build-and-test:
          name: build-and-test-mysql
          script: ./build-and-test-all-mysql.sh
          requires:
            - build-and-test-mysql-mysql-8-multi-arch
      - build-and-test/build-and-test:
          name: build-and-test-mysql8
          script: ./build-and-test-all-mysql8.sh
          requires:
            - build-and-test-mysql-mysql-8-multi-arch
      - build-and-test/build-and-test:
          name: build-and-test-mariadb
          script: ./build-and-test-all-mariadb.sh
          requires:
            - build-and-test-mysql-mysql-8-multi-arch
      - build-and-test/build-and-test:
          name: build-and-test-mssql
          script: ./build-and-test-all-mssql.sh
          requires:
            - build-and-test-mysql-mysql-8-multi-arch
      - build-and-test/build-and-test:
          name: build-and-test-postgres
          script: ./build-and-test-all-postgres.sh
          requires:
            - build-and-test-mysql-mysql-8-multi-arch
      - build-and-test/build-and-test:
          name: deploy-artifacts
          context:
            - publish
          requires:
            - build-and-test-mysql
            - build-and-test-mysql8
            - build-and-test-mariadb
            - build-and-test-mssql
            - build-and-test-postgres
          script: ./deploy-artifacts.sh
