dependencies {
    api project (":eventuate-common-jdbc")

    annotationProcessor "io.micronaut:micronaut-inject-java:$micronautVersion"
    annotationProcessor "io.micronaut:micronaut-validation:$micronautVersion"
    annotationProcessor "io.micronaut.configuration:micronaut-openapi:$micronautVersion"
    api "io.micronaut:micronaut-inject:$micronautVersion"
    api "io.micronaut:micronaut-validation:$micronautVersion"
    compileOnly "jakarta.annotation:jakarta.annotation-api:2.1.1"
    implementation "jakarta.inject:jakarta.inject-api:2.0.1"
    api "io.micronaut:micronaut-runtime:$micronautVersion"
}

test {
    systemProperty 'db.id.used', dbIdUsed
    if (project.hasProperty("eventuateOutboxId"))
        systemProperty 'eventuate.outbox.id', eventuateOutboxId
    useJUnitPlatform()
}
