FROM mysql/mysql-server:8.0.27-1.2.6-server

COPY replication.cnf /etc/my.cnf

HEALTHCHECK --interval=2s --retries=60 CMD /healthcheck.sh

RUN microdnf install gettext \
      && microdnf clean all

COPY 0.activate-additional-scripts.sh /docker-entrypoint-initdb.d
COPY 0.configure-root-user.sh /docker-entrypoint-initdb.d

RUN mkdir /additional-scripts
COPY 1.create-database.sql /additional-scripts
COPY 2.initialize-database.sql /additional-scripts
COPY 3.initialize-database.sql /additional-scripts
COPY 3.create-message-table.sql /additional-scripts
COPY 4.initialize-database-json.sql /additional-scripts
COPY 5.initialize-database-db-id.sql /additional-scripts

RUN touch /docker-entrypoint-initdb.d/1.create-database.sql \
          /docker-entrypoint-initdb.d/2.initialize-database.sql \
          /docker-entrypoint-initdb.d/3.initialize-database.sql \
          /docker-entrypoint-initdb.d/4.initialize-database-json.sql \
          /docker-entrypoint-initdb.d/5.initialize-database-db-id.sql \
          /docker-entrypoint-initdb.d/6.configure-users.sql

RUN chown mysql -R /docker-entrypoint-initdb.d /additional-scripts
