FROM mysql/mysql-server:8.0.27-1.2.6-server

COPY replication.cnf /etc/my.cnf
COPY 0.configure-root-user.sh /docker-entrypoint-initdb.d

RUN touch /docker-entrypoint-initdb.d/6.configure-users.sql

RUN chown mysql -R /docker-entrypoint-initdb.d
