FROM mysql/mysql-server:8.0.27-1.2.6-server

COPY replication.cnf /etc/my.cnf

COPY 0.activate-additional-scripts.sh /docker-entrypoint-initdb.d
COPY 0.multi-arch.activate-additional-scripts.sh /docker-entrypoint-initdb.d
COPY 1.initialize-database.sql /docker-entrypoint-initdb.d
COPY 2.initialize-database.sql /docker-entrypoint-initdb.d

RUN mkdir /additional-scripts
COPY 3.initialize-database-json.sql /additional-scripts
COPY 4.initialize-database-db-id.sql /additional-scripts

RUN touch /docker-entrypoint-initdb.d/3.initialize-database-json.sql \
 /docker-entrypoint-initdb.d/4.initialize-database-db-id.sql \
 /docker-entrypoint-initdb.d/5.configure-users.sql

RUN chown mysql -R /docker-entrypoint-initdb.d /additional-scripts
