dependencies {
    api "org.springframework.boot:spring-boot-starter-flyway:$springBootVersion"
    api "org.flywaydb:flyway-core:$flywayVersion"
    api project(":eventuate-common-spring-jdbc")

    runtimeOnly "org.flywaydb:flyway-mysql:$flywayVersion"
    runtimeOnly "org.flywaydb:flyway-sqlserver:$flywayVersion"
    runtimeOnly "org.flywaydb:flyway-database-postgresql:$flywayVersion"

    testImplementation project(":eventuate-common-testcontainers")

    testImplementation "org.springframework.boot:spring-boot-starter-flyway-test:$springBootVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-jdbc-test:$springBootVersion"
    testImplementation "org.testcontainers:testcontainers:$testContainersVersion"

}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
