FROM postgres:13.13-bullseye

RUN  apt-get update \
    && apt-get install -y postgresql-13-wal2json \
    && rm -rf /var/lib/apt/lists/*

# Copy the custom configuration which will be passed down to the server (using a .sample file is the preferred way of doing it by
# the base Docker image)
COPY postgresql.conf.sample /usr/share/postgresql/postgresql.conf.sample

# Copy the script which will initialize the replication permissions
COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

